# Generated by Django 4.2.6 on 2023-10-07 23:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authtoken", "0003_tokenproxy"),
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("api", "0002_customuser_item_quantity_alter_item_store_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomUser",
            new_name="ApiUser",
        ),
    ]
